import pg from "pg"; import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
const c = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await c.connect();
const imp = (await c.query("select id from impressoras limit 1")).rows[0].id;
await c.query("update impressoras set impressora_windows='Elgin L42PRO' where id=$1", [imp]);
const etq = (await c.query("select id from etiquetas order by criado_em desc limit 1")).rows[0].id;
await c.query("update etiquetas set impressora_id=$1, impressao_solicitada_em=now(), impresso_em=null where id=$2", [imp, etq]);
console.log("preparado etq="+etq);
await c.end();
