-- Numeração das comandas por caixa (regra do Rafael):
--  - salão/balcão/garçom: do 1 em diante, reiniciando a cada abertura de caixa;
--  - balança: numerada pelo PRÓPRIO agente, a partir de numero_inicial_balanca
--    (padrão 200), também reiniciando quando o caixa abre — e imprime na hora.
-- Pra o agente mandar o número, a coluna deixa de ser "GENERATED ALWAYS".
alter table public.pdv_comandas alter column numero set generated by default;

create or replace function public.pdv_reiniciar_numeracao()
returns void language sql security definer set search_path = public as $$
  select setval('public.pdv_comandas_numero_seq', 1, false);
$$;
grant execute on function public.pdv_reiniciar_numeracao() to authenticated;

insert into public.pdv_config (chave, valor)
select 'numero_inicial_balanca', '200'
where not exists (select 1 from public.pdv_config where chave = 'numero_inicial_balanca');
